### ISSUE TITLE
Cluster configuration gets broken after some time

### ISSUE THREAD

**Issue by qbast** [banzaicloud/kafka-operator#187] opened 2019-11-06 13:20 UTC
**Describe the bug**
About a day or two after creating a cluster, I find it broken with first broken in Pending state. This is caused by KafkaCluster resource being modified in a way that sets wrong NodeAffinity for the first broker.

**Steps to reproduce the issue:**
I am not sure how to trigger this.

**Expected behavior**
KafkaCluster resource should not be reconfigured into broken state.

**Additional context**
Using operator 0.2.3 installed via helm in GKE (1.14.7-gke.14) regional  private cluster (3 zones) . 

Right after creating and starting of a new cluster, broker config looks like this:

```
  Brokers:
    Broker Config Group:  default
    Id:                   0
    Broker Config Group:  default
    Id:                   1
    Broker Config Group:  default
    Id:                   2
```

A day or two later, I find none of brokers running and the first one in Pending state (with message `  Warning  FailedScheduling   2m48s (x423 over 10h)   default-scheduler   0/5 nodes are available: 2 node(s) had volume node affinity conflict, 3 node(s) didn't match node selector.`) 

This is caused by wrong NodeAffinity set by the operator.
Part of 'describe kafkacluster kafka' in invalid state:
```
  Brokers:
    Broker Config:
      Node Affinity:
        Required During Scheduling Ignored During Execution:
          Node Selector Terms:
            Match Expressions:
              Key:       failure-domain.beta.kubernetes.io/zone
              Operator:  In
              Values:
                europe-west3-a
              Key:       failure-domain.beta.kubernetes.io/region
              Operator:  In
              Values:
                europe-west3
    Broker Config Group:  default       
    Id:                   0             
    Broker Config Group:  default       
    Id:                   1             
    Broker Config Group:  default       
    Id:                   2             
```

This is completely wrong, as broker 0 is using PV in zone b. Editing kafkacluster resource and removing wrong affinity allows the cluster to start again.
Why the operator sets node affinity at all? Kubernetes should be able to figure out right zone on its own.

**Comment by baluchicken** [comment] 2019-11-08 10:40
Thanks for reporting this issue we are going to investigate this and get back to you with our findings.

**Comment by baluchicken** [comment] 2019-11-08 15:43
@qbast I tried to reproduce your error on a cluster with the configs you mentioned. I failed. The operator now puts the node affinity to the cr specs just before it terminates a failed pod. It fetches the pod in error and determines its node, so honestly I do not understand how this can happened.
Although, you are absolutely right that the operator should not place any node affinity at all, because the Kubernetes will by default schedule the pod to a zone where the PV can be reattached. I will create a PR which takes care of this soon.

**Comment by qbast** [comment] 2019-11-08 15:49
I am not sure what exactly triggers it (I suspect at least once it was GKE node auto-upgrade) but in my case it happened 4 times in 5 days (twice in two environments). I am currently running modified operator with the operation to set affinity and owner references commented out and it is finally stable.

**Comment by baluchicken** [comment] 2019-11-08 15:55
Thanks for the info we are going to address those things in the next release, thanks for reporting this issue.

**Comment by baluchicken** [comment] 2019-11-11 09:33
We just merged the fix for this, thanks for reporting it.

**Closed** 2019-11-11 09:32 UTC
Labels: bug, community
